def plot_learning_curve(history,ii):
    plt.plot(history.history['acc'])
    #plt.plot(history.history['categorical_accuracy'])    
    #plt.plot(history.history['val_categorical_accuracy'])
    plt.plot(history.history['val_acc'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.savefig('./accuracy_curve' + str(ii) + '.png')
    plt.clf()
    # summarize history for loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.savefig('./loss_curve'+ str(ii) + '.png')
